package bbdd.pojos;
// Generated 15 ene 2025, 23:24:11 by Hibernate Tools 6.5.1.Final

/**
 * Alumno generated by hbm2java
 */
public class Alumno implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3216931709465619208L;
	private int id;
	private Usuario usuario;

	public Alumno() {
	}

	public Alumno(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
