package bbdd.pojos;
// Generated 15 ene 2025, 23:24:11 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4505678960662496638L;
	private int id;
	private String nombre;
	private Integer curso;
	private Set horarios = new HashSet(0);
	private Set ciclos = new HashSet(0);

	public Asignatura() {
	}

	public Asignatura(int id) {
		this.id = id;
	}

	public Asignatura(int id, String nombre, Integer curso, Set horarios, Set ciclos) {
		this.id = id;
		this.nombre = nombre;
		this.curso = curso;
		this.horarios = horarios;
		this.ciclos = ciclos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getCurso() {
		return this.curso;
	}

	public void setCurso(Integer curso) {
		this.curso = curso;
	}

	public Set getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set horarios) {
		this.horarios = horarios;
	}

	public Set getCiclos() {
		return this.ciclos;
	}

	public void setCiclos(Set ciclos) {
		this.ciclos = ciclos;
	}

}
