package bbdd.pojos;
// Generated 15 ene 2025, 17:22:51 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas implements java.io.Serializable {

	private Long id;
	private Ciclos ciclos;
	private String nombre;
	private String descripcion;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Timestamp deletedAt;
	private Set horarioses = new HashSet(0);
	private Set asignaturaUsuarioHorarios = new HashSet(0);

	public Asignaturas() {
	}

	public Asignaturas(Ciclos ciclos, String nombre, String descripcion) {
		this.ciclos = ciclos;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public Asignaturas(Ciclos ciclos, String nombre, String descripcion, Timestamp createdAt, Timestamp updatedAt,
			Timestamp deletedAt, Set horarioses, Set asignaturaUsuarioHorarios) {
		this.ciclos = ciclos;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.horarioses = horarioses;
		this.asignaturaUsuarioHorarios = asignaturaUsuarioHorarios;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Ciclos getCiclos() {
		return this.ciclos;
	}

	public void setCiclos(Ciclos ciclos) {
		this.ciclos = ciclos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Timestamp getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Timestamp deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getHorarioses() {
		return this.horarioses;
	}

	public void setHorarioses(Set horarioses) {
		this.horarioses = horarioses;
	}

	public Set getAsignaturaUsuarioHorarios() {
		return this.asignaturaUsuarioHorarios;
	}

	public void setAsignaturaUsuarioHorarios(Set asignaturaUsuarioHorarios) {
		this.asignaturaUsuarioHorarios = asignaturaUsuarioHorarios;
	}

}
