package bbdd.pojos;
// Generated 15 ene 2025, 17:22:51 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * AsignaturaUsuarioHorario generated by hbm2java
 */
public class AsignaturaUsuarioHorario implements java.io.Serializable {

	private Long id;
	private Horarios horarios;
	private Users users;
	private Asignaturas asignaturas;
	private Timestamp createdAt;
	private Timestamp updatedAt;

	public AsignaturaUsuarioHorario() {
	}

	public AsignaturaUsuarioHorario(Horarios horarios, Users users, Asignaturas asignaturas) {
		this.horarios = horarios;
		this.users = users;
		this.asignaturas = asignaturas;
	}

	public AsignaturaUsuarioHorario(Horarios horarios, Users users, Asignaturas asignaturas, Timestamp createdAt,
			Timestamp updatedAt) {
		this.horarios = horarios;
		this.users = users;
		this.asignaturas = asignaturas;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Horarios getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Horarios horarios) {
		this.horarios = horarios;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Asignaturas getAsignaturas() {
		return this.asignaturas;
	}

	public void setAsignaturas(Asignaturas asignaturas) {
		this.asignaturas = asignaturas;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

}
