package bbdd.pojos;
// Generated 15 ene 2025, 17:22:51 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * CicloUsuario generated by hbm2java
 */
public class CicloUsuario implements java.io.Serializable {

	private Long id;
	private Users users;
	private Ciclos ciclos;
	private Timestamp fechaMatricula;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Timestamp deletedAt;

	public CicloUsuario() {
	}

	public CicloUsuario(Users users, Ciclos ciclos, Timestamp fechaMatricula) {
		this.users = users;
		this.ciclos = ciclos;
		this.fechaMatricula = fechaMatricula;
	}

	public CicloUsuario(Users users, Ciclos ciclos, Timestamp fechaMatricula, Timestamp createdAt, Timestamp updatedAt,
			Timestamp deletedAt) {
		this.users = users;
		this.ciclos = ciclos;
		this.fechaMatricula = fechaMatricula;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Ciclos getCiclos() {
		return this.ciclos;
	}

	public void setCiclos(Ciclos ciclos) {
		this.ciclos = ciclos;
	}

	public Timestamp getFechaMatricula() {
		return this.fechaMatricula;
	}

	public void setFechaMatricula(Timestamp fechaMatricula) {
		this.fechaMatricula = fechaMatricula;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Timestamp getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Timestamp deletedAt) {
		this.deletedAt = deletedAt;
	}

}
