package bbdd.pojos;
// Generated 15 ene 2025, 17:22:51 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Ciclos generated by hbm2java
 */
public class Ciclos implements java.io.Serializable {

	private Long id;
	private String nombre;
	private int curso;
	private String descripcion;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Timestamp deletedAt;
	private Set asignaturases = new HashSet(0);
	private Set cicloUsuarios = new HashSet(0);

	public Ciclos() {
	}

	public Ciclos(String nombre, int curso, String descripcion) {
		this.nombre = nombre;
		this.curso = curso;
		this.descripcion = descripcion;
	}

	public Ciclos(String nombre, int curso, String descripcion, Timestamp createdAt, Timestamp updatedAt,
			Timestamp deletedAt, Set asignaturases, Set cicloUsuarios) {
		this.nombre = nombre;
		this.curso = curso;
		this.descripcion = descripcion;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.asignaturases = asignaturases;
		this.cicloUsuarios = cicloUsuarios;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getCurso() {
		return this.curso;
	}

	public void setCurso(int curso) {
		this.curso = curso;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Timestamp getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Timestamp deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getAsignaturases() {
		return this.asignaturases;
	}

	public void setAsignaturases(Set asignaturases) {
		this.asignaturases = asignaturases;
	}

	public Set getCicloUsuarios() {
		return this.cicloUsuarios;
	}

	public void setCicloUsuarios(Set cicloUsuarios) {
		this.cicloUsuarios = cicloUsuarios;
	}

}
