package bbdd.pojos;
// Generated 15 ene 2025, 23:24:11 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ciclo generated by hbm2java
 */
public class Ciclo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4200595536796381527L;
	private int id;
	private Integer codigo;
	private String nombre;
	private String descripcion;
	private Set asignaturas = new HashSet(0);
	private Set usuarios = new HashSet(0);

	public Ciclo() {
	}

	public Ciclo(int id) {
		this.id = id;
	}

	public Ciclo(int id, Integer codigo, String nombre, String descripcion, Set asignaturas, Set usuarios) {
		this.id = id;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.asignaturas = asignaturas;
		this.usuarios = usuarios;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getAsignaturas() {
		return this.asignaturas;
	}

	public void setAsignaturas(Set asignaturas) {
		this.asignaturas = asignaturas;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
