package bbdd.pojos;
// Generated 15 ene 2025, 23:24:11 by Hibernate Tools 6.5.1.Final

/**
 * Cita generated by hbm2java
 */
public class Cita implements java.io.Serializable {

	private CitaId id;
	private Reunion reunion;
	private Usuario usuarioByIdProfesor;
	private Usuario usuarioByIdAlumno;

	public Cita() {
	}

	public Cita(CitaId id, Reunion reunion, Usuario usuarioByIdProfesor, Usuario usuarioByIdAlumno) {
		this.id = id;
		this.reunion = reunion;
		this.usuarioByIdProfesor = usuarioByIdProfesor;
		this.usuarioByIdAlumno = usuarioByIdAlumno;
	}

	public CitaId getId() {
		return this.id;
	}

	public void setId(CitaId id) {
		this.id = id;
	}

	public Reunion getReunion() {
		return this.reunion;
	}

	public void setReunion(Reunion reunion) {
		this.reunion = reunion;
	}

	public Usuario getUsuarioByIdProfesor() {
		return this.usuarioByIdProfesor;
	}

	public void setUsuarioByIdProfesor(Usuario usuarioByIdProfesor) {
		this.usuarioByIdProfesor = usuarioByIdProfesor;
	}

	public Usuario getUsuarioByIdAlumno() {
		return this.usuarioByIdAlumno;
	}

	public void setUsuarioByIdAlumno(Usuario usuarioByIdAlumno) {
		this.usuarioByIdAlumno = usuarioByIdAlumno;
	}

}
