package bbdd.pojos;
// Generated 15 ene 2025, 23:24:11 by Hibernate Tools 6.5.1.Final

/**
 * CitaId generated by hbm2java
 */
public class CitaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3259913589188567277L;
	private int idAlumno;
	private int idProfesor;
	private int idReunion;

	public CitaId() {
	}

	public CitaId(int idAlumno, int idProfesor, int idReunion) {
		this.idAlumno = idAlumno;
		this.idProfesor = idProfesor;
		this.idReunion = idReunion;
	}

	public int getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(int idAlumno) {
		this.idAlumno = idAlumno;
	}

	public int getIdProfesor() {
		return this.idProfesor;
	}

	public void setIdProfesor(int idProfesor) {
		this.idProfesor = idProfesor;
	}

	public int getIdReunion() {
		return this.idReunion;
	}

	public void setIdReunion(int idReunion) {
		this.idReunion = idReunion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CitaId))
			return false;
		CitaId castOther = (CitaId) other;

		return (this.getIdAlumno() == castOther.getIdAlumno()) && (this.getIdProfesor() == castOther.getIdProfesor())
				&& (this.getIdReunion() == castOther.getIdReunion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAlumno();
		result = 37 * result + this.getIdProfesor();
		result = 37 * result + this.getIdReunion();
		return result;
	}

}
