package bbdd.pojos;
// Generated 15 ene 2025, 23:24:11 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * CursosExternos generated by hbm2java
 */
public class CursosExternos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3579454587834333368L;
	private Integer id;
	private String titulo;
	private String descripcion;
	private Date fechaInicio;
	private Date fechaFin;
	private String horario;
	private String lugar;
	private String contacto;
	private String cicloFormativo;
	private Integer curso;
	private String asignatura;

	public CursosExternos() {
	}

	public CursosExternos(String titulo, String descripcion, Date fechaInicio, Date fechaFin, String horario,
			String lugar, String contacto, String cicloFormativo, Integer curso, String asignatura) {
		this.titulo = titulo;
		this.descripcion = descripcion;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.horario = horario;
		this.lugar = lugar;
		this.contacto = contacto;
		this.cicloFormativo = cicloFormativo;
		this.curso = curso;
		this.asignatura = asignatura;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getHorario() {
		return this.horario;
	}

	public void setHorario(String horario) {
		this.horario = horario;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	public String getCicloFormativo() {
		return this.cicloFormativo;
	}

	public void setCicloFormativo(String cicloFormativo) {
		this.cicloFormativo = cicloFormativo;
	}

	public Integer getCurso() {
		return this.curso;
	}

	public void setCurso(Integer curso) {
		this.curso = curso;
	}

	public String getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(String asignatura) {
		this.asignatura = asignatura;
	}

}
