package bbdd.pojos;
// Generated 15 ene 2025, 23:24:11 by Hibernate Tools 6.5.1.Final

/**
 * Horario generated by hbm2java
 */
public class Horario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1576218390331283559L;
	private Integer id;
	private Asignatura asignatura;
	private Usuario usuario;
	private String dia;
	private String tipo;
	private String aula;

	public Horario() {
	}

	public Horario(Usuario usuario, String dia, String tipo) {
		this.usuario = usuario;
		this.dia = dia;
		this.tipo = tipo;
	}

	public Horario(Asignatura asignatura, Usuario usuario, String dia, String tipo, String aula) {
		this.asignatura = asignatura;
		this.usuario = usuario;
		this.dia = dia;
		this.tipo = tipo;
		this.aula = aula;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getAula() {
		return this.aula;
	}

	public void setAula(String aula) {
		this.aula = aula;
	}

}
