package bbdd.pojos;
// Generated 15 ene 2025, 17:22:51 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Horarios generated by hbm2java
 */
public class Horarios implements java.io.Serializable {

	private HorariosId id;
	private Users users;
	private Asignaturas asignaturas;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Timestamp deletedAt;
	private Set asignaturaUsuarioHorarios = new HashSet(0);

	public Horarios() {
	}

	public Horarios(HorariosId id, Users users, Asignaturas asignaturas) {
		this.id = id;
		this.users = users;
		this.asignaturas = asignaturas;
	}

	public Horarios(HorariosId id, Users users, Asignaturas asignaturas, Timestamp createdAt, Timestamp updatedAt,
			Timestamp deletedAt, Set asignaturaUsuarioHorarios) {
		this.id = id;
		this.users = users;
		this.asignaturas = asignaturas;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.asignaturaUsuarioHorarios = asignaturaUsuarioHorarios;
	}

	public HorariosId getId() {
		return this.id;
	}

	public void setId(HorariosId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Asignaturas getAsignaturas() {
		return this.asignaturas;
	}

	public void setAsignaturas(Asignaturas asignaturas) {
		this.asignaturas = asignaturas;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Timestamp getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Timestamp deletedAt) {
		this.deletedAt = deletedAt;
	}

	public Set getAsignaturaUsuarioHorarios() {
		return this.asignaturaUsuarioHorarios;
	}

	public void setAsignaturaUsuarioHorarios(Set asignaturaUsuarioHorarios) {
		this.asignaturaUsuarioHorarios = asignaturaUsuarioHorarios;
	}

}
