package bbdd.pojos;
// Generated 15 ene 2025, 23:24:11 by Hibernate Tools 6.5.1.Final

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6483521363879212894L;
	private int id;
	private Usuario usuario;

	public Profesor() {
	}

	public Profesor(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
