package bbdd.pojos;
// Generated 15 ene 2025, 23:24:11 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Reunion generated by hbm2java
 */
public class Reunion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8372831231721733675L;
	private int id;
	private Timestamp fechaHoraInicio;
	private Timestamp fechaHoraFin;
	private String estado;
	private String comentario;
	private Set citas = new HashSet(0);

	public Reunion() {
	}

	public Reunion(int id) {
		this.id = id;
	}

	public Reunion(int id, Timestamp fechaHoraInicio, Timestamp fechaHoraFin, String estado, String comentario,
			Set citas) {
		this.id = id;
		this.fechaHoraInicio = fechaHoraInicio;
		this.fechaHoraFin = fechaHoraFin;
		this.estado = estado;
		this.comentario = comentario;
		this.citas = citas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Timestamp getFechaHoraInicio() {
		return this.fechaHoraInicio;
	}

	public void setFechaHoraInicio(Timestamp fechaHoraInicio) {
		this.fechaHoraInicio = fechaHoraInicio;
	}

	public Timestamp getFechaHoraFin() {
		return this.fechaHoraFin;
	}

	public void setFechaHoraFin(Timestamp fechaHoraFin) {
		this.fechaHoraFin = fechaHoraFin;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Set getCitas() {
		return this.citas;
	}

	public void setCitas(Set citas) {
		this.citas = citas;
	}

}
