package bbdd.pojos;
// Generated 15 ene 2025, 17:22:51 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;

/**
 * Reunions generated by hbm2java
 */
public class Reunions implements java.io.Serializable {

	private Long id;
	private Users usersByReceptorId;
	private Users usersByEmisorId;
	private String comentario;
	private String estado;
	private Timestamp fechaHoraInicio;
	private Timestamp fechaHoraFin;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Timestamp deletedAt;

	public Reunions() {
	}

	public Reunions(String comentario, String estado, Timestamp fechaHoraInicio, Timestamp fechaHoraFin) {
		this.comentario = comentario;
		this.estado = estado;
		this.fechaHoraInicio = fechaHoraInicio;
		this.fechaHoraFin = fechaHoraFin;
	}

	public Reunions(Users usersByReceptorId, Users usersByEmisorId, String comentario, String estado,
			Timestamp fechaHoraInicio, Timestamp fechaHoraFin, Timestamp createdAt, Timestamp updatedAt,
			Timestamp deletedAt) {
		this.usersByReceptorId = usersByReceptorId;
		this.usersByEmisorId = usersByEmisorId;
		this.comentario = comentario;
		this.estado = estado;
		this.fechaHoraInicio = fechaHoraInicio;
		this.fechaHoraFin = fechaHoraFin;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Users getUsersByReceptorId() {
		return this.usersByReceptorId;
	}

	public void setUsersByReceptorId(Users usersByReceptorId) {
		this.usersByReceptorId = usersByReceptorId;
	}

	public Users getUsersByEmisorId() {
		return this.usersByEmisorId;
	}

	public void setUsersByEmisorId(Users usersByEmisorId) {
		this.usersByEmisorId = usersByEmisorId;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Timestamp getFechaHoraInicio() {
		return this.fechaHoraInicio;
	}

	public void setFechaHoraInicio(Timestamp fechaHoraInicio) {
		this.fechaHoraInicio = fechaHoraInicio;
	}

	public Timestamp getFechaHoraFin() {
		return this.fechaHoraFin;
	}

	public void setFechaHoraFin(Timestamp fechaHoraFin) {
		this.fechaHoraFin = fechaHoraFin;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Timestamp getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Timestamp deletedAt) {
		this.deletedAt = deletedAt;
	}

}
