package bbdd.pojos;
// Generated 15 ene 2025, 17:22:51 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Long id;
	private Rols rols;
	private String user;
	private String surname;
	private String tel1;
	private String tel2;
	private String address;
	private String dni;
	private String name;
	private String email;
	private Timestamp emailVerifiedAt;
	private String password;
	private String rememberToken;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Timestamp deletedAt;
	private byte[] photo;
	private Set cicloUsuarios = new HashSet(0);
	private Set reunionsesForReceptorId = new HashSet(0);
	private Set reunionsesForEmisorId = new HashSet(0);
	private Set horarioses = new HashSet(0);
	private Set asignaturaUsuarioHorarios = new HashSet(0);

	public Users() {
	}

	public Users(String name, String email, String password) {
		this.name = name;
		this.email = email;
		this.password = password;
	}

	public Users(Rols rols, String user, String surname, String tel1, String tel2, String address, String dni,
			String name, String email, Timestamp emailVerifiedAt, String password, String rememberToken,
			Timestamp createdAt, Timestamp updatedAt, Timestamp deletedAt, byte[] photo, Set cicloUsuarios,
			Set reunionsesForReceptorId, Set reunionsesForEmisorId, Set horarioses, Set asignaturaUsuarioHorarios) {
		this.rols = rols;
		this.user = user;
		this.surname = surname;
		this.tel1 = tel1;
		this.tel2 = tel2;
		this.address = address;
		this.dni = dni;
		this.name = name;
		this.email = email;
		this.emailVerifiedAt = emailVerifiedAt;
		this.password = password;
		this.rememberToken = rememberToken;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.photo = photo;
		this.cicloUsuarios = cicloUsuarios;
		this.reunionsesForReceptorId = reunionsesForReceptorId;
		this.reunionsesForEmisorId = reunionsesForEmisorId;
		this.horarioses = horarioses;
		this.asignaturaUsuarioHorarios = asignaturaUsuarioHorarios;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Rols getRols() {
		return this.rols;
	}

	public void setRols(Rols rols) {
		this.rols = rols;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getTel1() {
		return this.tel1;
	}

	public void setTel1(String tel1) {
		this.tel1 = tel1;
	}

	public String getTel2() {
		return this.tel2;
	}

	public void setTel2(String tel2) {
		this.tel2 = tel2;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Timestamp getEmailVerifiedAt() {
		return this.emailVerifiedAt;
	}

	public void setEmailVerifiedAt(Timestamp emailVerifiedAt) {
		this.emailVerifiedAt = emailVerifiedAt;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRememberToken() {
		return this.rememberToken;
	}

	public void setRememberToken(String rememberToken) {
		this.rememberToken = rememberToken;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Timestamp getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Timestamp deletedAt) {
		this.deletedAt = deletedAt;
	}

	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	public Set getCicloUsuarios() {
		return this.cicloUsuarios;
	}

	public void setCicloUsuarios(Set cicloUsuarios) {
		this.cicloUsuarios = cicloUsuarios;
	}

	public Set getReunionsesForReceptorId() {
		return this.reunionsesForReceptorId;
	}

	public void setReunionsesForReceptorId(Set reunionsesForReceptorId) {
		this.reunionsesForReceptorId = reunionsesForReceptorId;
	}

	public Set getReunionsesForEmisorId() {
		return this.reunionsesForEmisorId;
	}

	public void setReunionsesForEmisorId(Set reunionsesForEmisorId) {
		this.reunionsesForEmisorId = reunionsesForEmisorId;
	}

	public Set getHorarioses() {
		return this.horarioses;
	}

	public void setHorarioses(Set horarioses) {
		this.horarioses = horarioses;
	}

	public Set getAsignaturaUsuarioHorarios() {
		return this.asignaturaUsuarioHorarios;
	}

	public void setAsignaturaUsuarioHorarios(Set asignaturaUsuarioHorarios) {
		this.asignaturaUsuarioHorarios = asignaturaUsuarioHorarios;
	}

}
