package bbdd.pojos;
// Generated 15 ene 2025, 23:24:11 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5132290117768949615L;
	private Integer id;
	private Ciclo ciclo;
	private String login;
	private String password;
	private String nombre;
	private String apellidos;
	private String email;
	private String telefono;
	private byte[] foto;
	private String tipoUsuario;
	private String cicloFormativo;
	private Integer curso;
	private Integer duales;
	private String dni;
	private String telefono1;
	private String telefono2;
	private Alumno alumno;
	private Set citasForIdProfesor = new HashSet(0);
	private Set horarios = new HashSet(0);
	private Profesor profesor;
	private Set citasForIdAlumno = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String login, String password, String tipoUsuario) {
		this.login = login;
		this.password = password;
		this.tipoUsuario = tipoUsuario;
	}

	public Usuario(Ciclo ciclo, String login, String password, String nombre, String apellidos, String email,
			String telefono, byte[] foto, String tipoUsuario, String cicloFormativo, Integer curso, Integer duales,
			String dni, String telefono1, String telefono2, Alumno alumno, Set citasForIdProfesor, Set horarios,
			Profesor profesor, Set citasForIdAlumno) {
		this.ciclo = ciclo;
		this.login = login;
		this.password = password;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
		this.telefono = telefono;
		this.foto = foto;
		this.tipoUsuario = tipoUsuario;
		this.cicloFormativo = cicloFormativo;
		this.curso = curso;
		this.duales = duales;
		this.dni = dni;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.alumno = alumno;
		this.citasForIdProfesor = citasForIdProfesor;
		this.horarios = horarios;
		this.profesor = profesor;
		this.citasForIdAlumno = citasForIdAlumno;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Ciclo getCiclo() {
		return this.ciclo;
	}

	public void setCiclo(Ciclo ciclo) {
		this.ciclo = ciclo;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public String getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(String tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	public String getCicloFormativo() {
		return this.cicloFormativo;
	}

	public void setCicloFormativo(String cicloFormativo) {
		this.cicloFormativo = cicloFormativo;
	}

	public Integer getCurso() {
		return this.curso;
	}

	public void setCurso(Integer curso) {
		this.curso = curso;
	}

	public Integer getDuales() {
		return this.duales;
	}

	public void setDuales(Integer duales) {
		this.duales = duales;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public Alumno getAlumno() {
		return this.alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	public Set getCitasForIdProfesor() {
		return this.citasForIdProfesor;
	}

	public void setCitasForIdProfesor(Set citasForIdProfesor) {
		this.citasForIdProfesor = citasForIdProfesor;
	}

	public Set getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set horarios) {
		this.horarios = horarios;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public Set getCitasForIdAlumno() {
		return this.citasForIdAlumno;
	}

	public void setCitasForIdAlumno(Set citasForIdAlumno) {
		this.citasForIdAlumno = citasForIdAlumno;
	}

}
